### ISSUE TITLE
Problems with installation on Windows 11

### ISSUE THREAD

**Issue by DobretaAndrzejewic** [petoncle/mousemaster#4] opened 2024-05-04 07:57 UTC
Hi, 

I did everything as said, changed the file name, clicked mousemaster.exe and such a thing appeared:
![Screenshot 2024-05-04 094539](https://github.com/petoncle/mousemaster/assets/58514348/22f64960-d356-422a-9220-f0420dae8da7)

Before I tried Neatmouse, but it had issues with the cursor going too far, then I tried Mouseable, and it worked fine, for more or less one day on both users' profiles on my PC. Then, the next day it worked fine (although it had problems working when the Task Manager window was open), but after changing the user, it stopped working, the program simply does not want to run. 

I also must say that in both programs, that is in Mousemaster and Mouseable, Windows and Norton treated them as potential malware and wanted to block them. 
Of course I  tried restarting the PC, installing the program again, running as administrator and so on. 

That's a pity, I started to really like the keyboard navigation:/

**Comment by petoncle** [comment] 2024-05-04 09:17
Hi @DobretaAndrzejewic, the window you are seeing is actually normal. The app is a command line app (for now), and that window you're seeing is the command line window. It contains logs which can be used for debugging and understanding what the program is doing. I understand that it's not very user friendly. But the good news is I don't see any error in the logs from the screenshot you shared, which means the app is working as intended.

However, if you're not able to control the mouse using the keyboard layout defined in the configuration file that you chose, please let me know and I'll do my best to help you make it work 🙂 

Regarding the antivirus treating it as a potential malware, that's annoying. I'm not sure yet what can be done about that problem.

**Comment by DobretaAndrzejewic** [comment] 2024-05-04 10:46
Ah, okay, you're right, it works indeed. Now I understand, I thought it's not working because I tried to use it after closing the command window, not realizing it's the program itself. Thanks a lot, I'll give it a try and if there will be some problems, I'll say:)
I think this app has potential. Have a nice day and thanks!

**Comment by petoncle** [comment] 2024-05-07 14:01
I'm closing this issue since the conversation with @DobretaAndrzejewic is continuing in issue https://github.com/petoncle/mousemaster/issues/5.

**Closed by petoncle** 2024-05-07 14:01 UTC
